/*
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package brevoModel;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.apache.commons.lang3.ObjectUtils;

/**
 * Body4
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-04-17T12:57:43.398+05:30")
public class Body4 {
  @SerializedName("name")
  private String name = null;

  @SerializedName("attributes")
  private Object attributes = null;

  @SerializedName("countryCode")
  private Long countryCode = null;

  public Body4 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of company
   * @return name
  **/
  @ApiModelProperty(example = "company", value = "Name of company")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Body4 attributes(Object attributes) {
    this.attributes = attributes;
    return this;
  }

   /**
   * Attributes for company update
   * @return attributes
  **/
  @ApiModelProperty(example = "{\"category\":\"label_2\",\"domain\":\"xyz\",\"date\":\"2022-05-04T00:00:00+05:30\",\"industry\":\"flipkart\",\"number_of_contacts\":1,\"number_of_employees\":100,\"owner\":\"5b1a17d914b73d35a76ca0c7\",\"phone_number\":\"81718441912\",\"revenue\":10000.34222}", value = "Attributes for company update")
  public Object getAttributes() {
    return attributes;
  }

  public void setAttributes(Object attributes) {
    this.attributes = attributes;
  }

  public Body4 countryCode(Long countryCode) {
    this.countryCode = countryCode;
    return this;
  }

   /**
   * Country code if phone_number is passed in attributes.
   * @return countryCode
  **/
  @ApiModelProperty(example = "91", value = "Country code if phone_number is passed in attributes.")
  public Long getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(Long countryCode) {
    this.countryCode = countryCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    Body4 body4 = (Body4) o;
    return ObjectUtils.equals(this.name, body4.name) &&
    ObjectUtils.equals(this.attributes, body4.attributes) &&
    ObjectUtils.equals(this.countryCode, body4.countryCode);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(name, attributes, countryCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body4 {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

