/*
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package brevoModel;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.apache.commons.lang3.ObjectUtils;

/**
 * GetSegmentsSegments
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-04-17T12:57:43.398+05:30")
public class GetSegmentsSegments {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("segmentName")
  private String segmentName = null;

  @SerializedName("categoryName")
  private String categoryName = null;

  @SerializedName("updatedAt")
  private String updatedAt = null;

  public GetSegmentsSegments id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * ID of the list
   * @return id
  **/
  @ApiModelProperty(example = "23", value = "ID of the list")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public GetSegmentsSegments segmentName(String segmentName) {
    this.segmentName = segmentName;
    return this;
  }

   /**
   * Name of the Segment
   * @return segmentName
  **/
  @ApiModelProperty(example = "My Segment", value = "Name of the Segment")
  public String getSegmentName() {
    return segmentName;
  }

  public void setSegmentName(String segmentName) {
    this.segmentName = segmentName;
  }

  public GetSegmentsSegments categoryName(String categoryName) {
    this.categoryName = categoryName;
    return this;
  }

   /**
   * Name of the Segment Category
   * @return categoryName
  **/
  @ApiModelProperty(example = "New Category", value = "Name of the Segment Category")
  public String getCategoryName() {
    return categoryName;
  }

  public void setCategoryName(String categoryName) {
    this.categoryName = categoryName;
  }

  public GetSegmentsSegments updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Updation UTC date-time of the segment (YYYY-MM-DDTHH:mm:ss.SSSZ)
   * @return updatedAt
  **/
  @ApiModelProperty(example = "2017-03-13T17:05:09Z", value = "Updation UTC date-time of the segment (YYYY-MM-DDTHH:mm:ss.SSSZ)")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    GetSegmentsSegments getSegmentsSegments = (GetSegmentsSegments) o;
    return ObjectUtils.equals(this.id, getSegmentsSegments.id) &&
    ObjectUtils.equals(this.segmentName, getSegmentsSegments.segmentName) &&
    ObjectUtils.equals(this.categoryName, getSegmentsSegments.categoryName) &&
    ObjectUtils.equals(this.updatedAt, getSegmentsSegments.updatedAt);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(id, segmentName, categoryName, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetSegmentsSegments {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    segmentName: ").append(toIndentedString(segmentName)).append("\n");
    sb.append("    categoryName: ").append(toIndentedString(categoryName)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

